version: '3.7'
services:
  publisher:
    build:
      context: ./publisher
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
  client:
    build:
      context: ./client
    stdin_open: true
    ports:
      - 80:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  rabbitmq-data:
